dofile(minetest.get_modpath("mighty_morphin") .. "/api.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/functions.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/arsenal.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/craftitems.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/communicators.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/crafts.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/rangers.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/morphing.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/privs.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/commands.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/command_center_materials.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/command_center_materials_crafting.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/teleportation_computer.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/abms.lua")
dofile(minetest.get_modpath("mighty_morphin") .. "/henchmen.lua")

minetest.register_on_dignode(function(digger)
	
end)